import { useMemo } from 'react'
import { CheckCircle2, XCircle } from 'lucide-react'
import { useDataset } from '../hooks/useDataset'
import { PageHeader, StatCard, ChartCard } from '../components/common/Cards'
import { BarList } from '../components/charts/Charts'
import { Callout } from '../components/common/Cards'
import { NOT_AVAILABLE } from '../constants'
import { fmtInt } from '../utils/stats'

export default function DataQuality() {
  const { quality: q, rows, companies, questions } = useDataset()
  const checks = useMemo(() => {
    if (!q) return []
    const pairSum = companies.reduce((s, c) => s + c.total, 0)
    return [
      ['Required columns present in every file', q.issues.missingColumns.length === 0],
      ['No missing values', q.issues.missingValues === 0],
      ['All difficulties are Easy / Medium / Hard', q.issues.invalidDifficulty === 0],
      ['Acceptance values within 0–100', q.issues.invalidAcceptance === 0],
      ['Frequency values within 0–100', q.issues.invalidFrequency === 0],
      ['All URLs valid', q.issues.invalidUrl === 0],
      ['No duplicate rows inside a file', q.issues.duplicateRowsInFile === 0],
      ['No conflicting titles for one problem ID', q.conflictingTitles.length === 0],
      ['No conflicting URLs for one problem ID', q.conflictingUrls.length === 0],
      ['Browser record count matches build output', rows === q.normalizedRecords && pairSum === rows],
      ['Browser company count matches build output', companies.length === q.companies],
      ['Browser unique-problem count matches build output', questions.length === q.uniqueProblems],
    ]
  }, [q, rows, companies, questions])
  if (!q) return <PageHeader title="Data Quality" description={`Build report (quality.json) ${NOT_AVAILABLE}`} />
  const files = Object.entries(q.recordsByFile).map(([name, value]) => ({ name, value }))
  return (
    <>
      <PageHeader title="Data Quality" description="Validation results generated by the dataset build script, plus runtime cross-checks in the browser." />
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        <StatCard label="Source files" value={fmtInt(q.sourceFiles)} /><StatCard label="Raw rows read" value={fmtInt(q.rawRows)} />
        <StatCard label="Normalized records" value={fmtInt(q.normalizedRecords)} hint="one per company-question pair" /><StatCard label="Rows merged across files" value={fmtInt(q.rowsMergedAcrossSourceFiles)} hint="same pair in several files" />
        <StatCard label="Companies" value={fmtInt(q.companies)} /><StatCard label="Unique problems" value={fmtInt(q.uniqueProblems)} />
        <StatCard label="Duplicate rows in a file" value={fmtInt(q.duplicateRowsInFile)} /><StatCard label="Pairs absent from all.csv" value={fmtInt(q.recordsWithoutAllCsv)} hint="frequency not available" />
      </div>
      <div className="mt-4 grid gap-4 lg:grid-cols-2">
        <section className="card p-4"><h2 className="mb-3 text-sm font-semibold">Validation checks</h2>
          <ul className="space-y-2">{checks.map(([label, ok]) => <li key={label} className="flex items-start gap-2 text-sm">{ok ? <CheckCircle2 className="mt-0.5 h-4 w-4 text-emerald-500" aria-label="Passed" /> : <XCircle className="mt-0.5 h-4 w-4 text-red-500" aria-label="Failed" />}<span>{label} <span className="sr-only">{ok ? 'passed' : 'failed'}</span></span></li>)}</ul></section>
        <ChartCard title="Raw rows by source file" height={260}><BarList data={files} nameWidth={150} valueLabel="Rows" /></ChartCard>
      </div>
      <div className="mt-4"><Callout>Duplicates in the browser are already removed: the build merges the same company-question pair found in several files into one record and keeps every source file name.</Callout></div>
    </>
  )
}
